name: Jest Tests

on:
  push:
    branches:
      - develop # Changer en la branche que vous souhaitez surveiller

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Changer en la version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
